# Generated by Django 4.2.7 on 2025-07-25 14:21

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0004_quotationtemplate_header_fields_config"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Skip problematic field renames that cause conflicts
        # The user field already exists from previous migrations
        
        # Skip adding fields that already exist to avoid conflicts
        
        # Rename Quotation fields
        migrations.RenameField(
            model_name="quotation",
            old_name="number",
            new_name="quotation_number",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="date",
            new_name="quotation_date",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="tax",
            new_name="total_tax",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="discount",
            new_name="total_discount",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="shipping",
            new_name="shipping_fee",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="total",
            new_name="grand_total",
        ),
        # Skip problematic field renames that cause conflicts
        # The user field already exists from previous migrations
        
        # Skip adding fields that already exist to avoid conflicts
        
        # Remove old fields from Quotation
        migrations.RemoveField(
            model_name="quotation",
            name="color_scheme",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="header_custom_fields",
        ),
        
        # Rename QuotationItem fields
        migrations.RenameField(
            model_name="quotationitem",
            old_name="total",
            new_name="line_total",
        ),
        
        # Skip adding fields that already exist to avoid conflicts
        
        # Update field attributes
        migrations.AlterField(
            model_name="quotation",
            name="quotation_number",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="quotation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quotations", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="client",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="quotations", to="clients.client"),
        ),
        migrations.AlterField(
            model_name="quotationtemplate",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quotation_templates", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="description",
            field=models.CharField(blank=True, help_text="Detailed description", max_length=500),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="quantity",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="unit_price",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["user", "-created_at"], name="quotations__user_id_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["quotation_number"], name="quotations__quotation_number_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["status"], name="quotations__status_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["quotation_date"], name="quotations__quotation_date_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["valid_until"], name="quotations__valid_until_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["client"], name="quotations__client_id_idx"),
        ),
        
        # Add Meta options
        migrations.AlterModelOptions(
            name="quotation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="quotationtemplate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="quotationitem",
            options={"ordering": ["id"]},
        ),
        
        # Add unique constraints
        migrations.AlterUniqueTogether(
            name="quotationtemplate",
            unique_together={("user", "name")},
        ),
    ]
