# Generated by Django 4.2.7 on 2025-09-24 12:26

from django.db import migrations, connection


def fix_quotation_template_user_id(apps, schema_editor):
    """
    Fix the user_id column conflict in quotations_quotationtemplate table
    """
    with connection.cursor() as cursor:
        # Check if the column exists and handle the conflict
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='quotations_quotationtemplate' 
            AND column_name='user_id'
        """)
        
        if cursor.fetchone():
            # Column exists, no need to add it
            pass
        else:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE quotations_quotationtemplate 
                ADD COLUMN user_id INTEGER REFERENCES accounts_user(id) ON DELETE CASCADE
            """)


def reverse_fix_quotation_template_user_id(apps, schema_editor):
    """
    Reverse migration - remove user_id column if it exists
    """
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='quotations_quotationtemplate' 
            AND column_name='user_id'
        """)
        
        if cursor.fetchone():
            cursor.execute("""
                ALTER TABLE quotations_quotationtemplate 
                DROP COLUMN user_id
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0009_quotation_conversion_date_and_more"),
    ]

    operations = [
        migrations.RunPython(
            fix_quotation_template_user_id,
            reverse_fix_quotation_template_user_id,
        ),
    ]
