# Generated by Django 4.2.7 on 2025-09-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0009_quotation_conversion_date_and_more"),
    ]

    operations = []
