# Generated by Django 4.2.7 on 2025-09-24 12:26

from django.db import migrations, connection


def fix_quotation_template_user_id(apps, schema_editor):
    """
    Fix the user_id column conflict in quotations_quotationtemplate table
    """
    with connection.cursor() as cursor:
        # For SQLite, we'll use PRAGMA to check table info
        try:
            cursor.execute("PRAGMA table_info(quotations_quotationtemplate)")
            columns = [row[1] for row in cursor.fetchall()]
            
            if 'user_id' not in columns:
                # Column doesn't exist, add it
                cursor.execute("""
                    ALTER TABLE quotations_quotationtemplate 
                    ADD COLUMN user_id INTEGER REFERENCES accounts_user(id) ON DELETE CASCADE
                """)
        except Exception:
            # If table doesn't exist, skip
            pass


def reverse_fix_quotation_template_user_id(apps, schema_editor):
    """
    Reverse migration - remove user_id column if it exists
    """
    with connection.cursor() as cursor:
        try:
            cursor.execute("PRAGMA table_info(quotations_quotationtemplate)")
            columns = [row[1] for row in cursor.fetchall()]
            
            if 'user_id' in columns:
                cursor.execute("""
                    ALTER TABLE quotations_quotationtemplate 
                    DROP COLUMN user_id
                """)
        except Exception:
            # If table doesn't exist, skip
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0009_quotation_conversion_date_and_more"),
    ]

    operations = [
        migrations.RunPython(
            fix_quotation_template_user_id,
            reverse_fix_quotation_template_user_id,
        ),
    ]
