# Generated by Django 4.2.7 on 2025-09-25 08:54

from django.db import migrations, models, connection
import django.db.models.deletion


def add_user_fields_if_not_exists(apps, schema_editor):
    """
    Add user fields only if they don't already exist
    """
    with connection.cursor() as cursor:
        # Check if user_id column exists in quotations_quotation table
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='quotations_quotation' 
            AND column_name='user_id'
        """)
        
        if not cursor.fetchone():
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE quotations_quotation 
                ADD COLUMN user_id INTEGER REFERENCES accounts_user(id) ON DELETE CASCADE
            """)
        
        # Check if user_id column exists in quotations_quotationtemplate table
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='quotations_quotationtemplate' 
            AND column_name='user_id'
        """)
        
        if not cursor.fetchone():
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE quotations_quotationtemplate 
                ADD COLUMN user_id INTEGER REFERENCES accounts_user(id) ON DELETE CASCADE
            """)


def reverse_add_user_fields(apps, schema_editor):
    """
    Remove user fields if they exist
    """
    with connection.cursor() as cursor:
        try:
            cursor.execute("ALTER TABLE quotations_quotation DROP COLUMN IF EXISTS user_id")
            cursor.execute("ALTER TABLE quotations_quotationtemplate DROP COLUMN IF EXISTS user_id")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0010_auto_20250924_1326"),
    ]

    operations = [
        migrations.RunPython(
            add_user_fields_if_not_exists,
            reverse_add_user_fields,
        ),
    ]
