# Generated by Django 4.2.7 on 2025-09-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0010_auto_20250924_1326"),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='user',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='quotationtemplate',
            name='user',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_templates', to='accounts.user'),
        ),
    ]
