# Generated by Django 4.2.7 on 2025-09-25 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotations", "0011_auto_20250925_1254"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="quotation",
            new_name="quotations__quotati_d2f33a_idx",
            old_name="quotations__quotation_number_idx",
        ),
        migrations.RenameIndex(
            model_name="quotation",
            new_name="quotations__status_2435f4_idx",
            old_name="quotations__status_idx",
        ),
        migrations.RenameIndex(
            model_name="quotation",
            new_name="quotations__quotati_eaed53_idx",
            old_name="quotations__quotation_date_idx",
        ),
        migrations.RenameIndex(
            model_name="quotation",
            new_name="quotations__client__bb8ebd_idx",
            old_name="quotations__client_id_idx",
        ),
        migrations.RemoveField(
            model_name="quotationtemplate",
            name="company",
        ),
        migrations.RemoveField(
            model_name="quotationtemplate",
            name="created_by",
        ),
        migrations.AddField(
            model_name="quotation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="valid_until",
            field=models.DateField(
                blank=True, help_text="Quotation validity period", null=True
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="product_service",
            field=models.CharField(
                blank=True, help_text="Product or service name", max_length=250
            ),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="accent_color",
            field=models.CharField(
                default="#e9ecef",
                help_text="Accent color for borders and highlights (hex code)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of this template"
            ),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="document_title",
            field=models.CharField(
                default="QUOTATION",
                help_text="Document title to display",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="footer_text",
            field=models.TextField(
                blank=True, help_text="Footer text to display on quotations"
            ),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Use as default template"
            ),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="number_prefix",
            field=models.CharField(
                default="QT", help_text="Quotation number prefix", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="primary_color",
            field=models.CharField(
                default="#1976d2", help_text="Primary color (hex code)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="secondary_color",
            field=models.CharField(
                default="#f8f9fa", help_text="Secondary color (hex code)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="show_bank_details",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="show_company_details",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="show_company_logo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="show_signature",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="text_color",
            field=models.CharField(
                default="#333333", help_text="Text color (hex code)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotation_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="other_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="quotationtemplate",
            name="default_terms",
            field=models.TextField(
                blank=True,
                default="This quotation is valid for 30 days from the date of issue",
                help_text="Default terms for new quotations",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quotation",
            unique_together={("user", "quotation_number")},
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["user", "-created_at"], name="quotations__user_id_57ceb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["valid_until"], name="quotations__valid_u_5c5317_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="company",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="created_by",
        ),
    ]
