# Generated by Django 4.2.7 on 2025-09-25 09:11

from django.db import migrations, models, connection


def add_missing_quotation_template_fields(apps, schema_editor):
    """
    Add all missing fields to quotations_quotationtemplate table
    """
    with connection.cursor() as cursor:
        # List of fields to add with their SQL definitions
        fields_to_add = [
            ("description", "TEXT DEFAULT ''"),
            ("primary_color", "VARCHAR(7) DEFAULT '#1976d2'"),
            ("secondary_color", "VARCHAR(7) DEFAULT '#f8f9fa'"),
            ("text_color", "VARCHAR(7) DEFAULT '#333333'"),
            ("accent_color", "VARCHAR(7) DEFAULT '#e9ecef'"),
            ("show_company_logo", "BOOLEAN DEFAULT TRUE"),
            ("show_company_details", "BOOLEAN DEFAULT TRUE"),
            ("show_bank_details", "BOOLEAN DEFAULT TRUE"),
            ("show_signature", "BOOLEAN DEFAULT TRUE"),
            ("document_title", "VARCHAR(100) DEFAULT 'QUOTATION'"),
            ("number_prefix", "VARCHAR(10) DEFAULT 'QT'"),
            ("default_terms", "TEXT DEFAULT 'This quotation is valid for 30 days from the date of issue'"),
            ("footer_text", "TEXT DEFAULT ''"),
            ("is_default", "BOOLEAN DEFAULT FALSE"),
        ]
        
        for field_name, field_definition in fields_to_add:
            # Check if column exists
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='quotations_quotationtemplate' 
                AND column_name=%s
            """, [field_name])
            
            if not cursor.fetchone():
                # Column doesn't exist, add it
                cursor.execute(f"""
                    ALTER TABLE quotations_quotationtemplate 
                    ADD COLUMN {field_name} {field_definition}
                """)


def add_missing_quotation_fields(apps, schema_editor):
    """
    Add all missing fields to quotations_quotation table
    """
    with connection.cursor() as cursor:
        # List of fields to add with their SQL definitions
        fields_to_add = [
            ("valid_until", "DATE"),
        ]
        
        for field_name, field_definition in fields_to_add:
            # Check if column exists
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='quotations_quotation' 
                AND column_name=%s
            """, [field_name])
            
            if not cursor.fetchone():
                # Column doesn't exist, add it
                cursor.execute(f"""
                    ALTER TABLE quotations_quotation 
                    ADD COLUMN {field_name} {field_definition}
                """)


def reverse_add_missing_fields(apps, schema_editor):
    """
    Remove the added fields
    """
    with connection.cursor() as cursor:
        try:
            # Remove quotation template fields
            template_fields = [
                "description", "primary_color", "secondary_color", "text_color", "accent_color",
                "show_company_logo", "show_company_details", "show_bank_details", "show_signature",
                "document_title", "number_prefix", "default_terms", "footer_text", "is_default"
            ]
            
            for field in template_fields:
                cursor.execute(f"ALTER TABLE quotations_quotationtemplate DROP COLUMN IF EXISTS {field}")
            
            # Remove quotation fields
            quotation_fields = ["valid_until"]
            for field in quotation_fields:
                cursor.execute(f"ALTER TABLE quotations_quotation DROP COLUMN IF EXISTS {field}")
                
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0011_auto_20250925_0954"),
    ]

    operations = [
        migrations.RunPython(
            add_missing_quotation_template_fields,
            reverse_add_missing_fields,
        ),
        migrations.RunPython(
            add_missing_quotation_fields,
            reverse_add_missing_fields,
        ),
    ]
