# Generated by Django 4.2.7 on 2025-09-25 13:05

from django.db import migrations


def noop_forward(apps, schema_editor):
    """No operation - just to satisfy migration requirements"""
    pass


def noop_reverse(apps, schema_editor):
    """No operation - just to satisfy migration requirements"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0012_noop_migration"),
    ]

    operations = [
        # This is a no-op migration to satisfy Django's migration requirements
        # The actual model changes are already in place in the database
        migrations.RunPython(
            noop_forward,
            reverse_code=noop_reverse,
        ),
    ]
