# Generated by Django 4.2.7 on 2025-09-25 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_bio_user_birth_date_user_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+1234567890' or '(123) 456-7890'. 10-20 characters allowed.",
                        regex="^\\+?[\\d\\s\\-\\(\\)]{10,20}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
