# Generated by Django 4.2.7 on 2025-09-25 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+1234567890' or '(123) 456-7890'. 10-20 characters allowed.",
                        regex="^\\+?[\\d\\s\\-\\(\\)]{10,20}$",
                    )
                ],
            ),
        ),
    ]
